
import __ASTRO_IMAGE_IMPORT_2mhree from "./images/customizing-user-information/cover.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fsample-docker-basics.md";
import __ASTRO_IMAGE_IMPORT_dFx36 from "./images/customizing-user-information/cover.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fsample-ansible-automation.md";
import __ASTRO_IMAGE_IMPORT_1xIVfm from "./images/customizing-user-information/cover.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fcustomizing-user-information.mdx";
import __ASTRO_IMAGE_IMPORT_2myHVG from "./images/customizing-theme-color-schemes/cover.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fcustomizing-theme-color-schemes.md";
import __ASTRO_IMAGE_IMPORT_Z1WcY7b from "./images/customizing-theme-color-schemes/cover.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fsample-kubernetes-operations.md";
import __ASTRO_IMAGE_IMPORT_1Bl4z0 from "./images/customizing-theme-color-schemes/cover.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fsample-gitlab-ci.md";
import __ASTRO_IMAGE_IMPORT_Z1u5auK from "./images/customizing-theme-color-schemes/cover.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fsample-rhel-hardening.md";
import __ASTRO_IMAGE_IMPORT_XaOiQ from "./images/customizing-user-information/cover.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fsample-openshift-routes.md";
import __ASTRO_IMAGE_IMPORT_1XPlKS from "./images/customizing-theme-color-schemes/cover.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fsample-satellite-patching.md";
import __ASTRO_IMAGE_IMPORT_2bYbAx from "./images/customizing-user-information/cover.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fsample-monitoring-stack.md";
import __ASTRO_IMAGE_IMPORT_rB8fC from "./images/pro-accountant/accnt.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fpro-accountant.mdx";
import __ASTRO_IMAGE_IMPORT_Z27euY2 from "./images/budget-wise/finance_app_concept.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Ffinance-app.mdx";
export default new Map([["./images/customizing-user-information/cover.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fsample-docker-basics.md", __ASTRO_IMAGE_IMPORT_2mhree], ["./images/customizing-user-information/cover.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fsample-ansible-automation.md", __ASTRO_IMAGE_IMPORT_dFx36], ["./images/customizing-user-information/cover.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fcustomizing-user-information.mdx", __ASTRO_IMAGE_IMPORT_1xIVfm], ["./images/customizing-theme-color-schemes/cover.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fcustomizing-theme-color-schemes.md", __ASTRO_IMAGE_IMPORT_2myHVG], ["./images/customizing-theme-color-schemes/cover.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fsample-kubernetes-operations.md", __ASTRO_IMAGE_IMPORT_Z1WcY7b], ["./images/customizing-theme-color-schemes/cover.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fsample-gitlab-ci.md", __ASTRO_IMAGE_IMPORT_1Bl4z0], ["./images/customizing-theme-color-schemes/cover.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fsample-rhel-hardening.md", __ASTRO_IMAGE_IMPORT_Z1u5auK], ["./images/customizing-user-information/cover.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fsample-openshift-routes.md", __ASTRO_IMAGE_IMPORT_XaOiQ], ["./images/customizing-theme-color-schemes/cover.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fsample-satellite-patching.md", __ASTRO_IMAGE_IMPORT_1XPlKS], ["./images/customizing-user-information/cover.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fsample-monitoring-stack.md", __ASTRO_IMAGE_IMPORT_2bYbAx], ["./images/pro-accountant/accnt.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fpro-accountant.mdx", __ASTRO_IMAGE_IMPORT_rB8fC], ["./images/budget-wise/finance_app_concept.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Ffinance-app.mdx", __ASTRO_IMAGE_IMPORT_Z27euY2]]);
		